package com.workshop.lab4;

import com.workshop.lab4.tools.FileSystemTools;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.TestPropertySource;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Integration test for the Lab 4 Developer Sidekick.
 *
 * <p>Validates that the {@link FileSystemTools} can list, read, and write
 * files within the sandbox, and that path traversal is blocked.</p>
 *
 * <p>Uses a minimal Spring context — only the {@link FileSystemTools} bean
 * is needed, so heavy infrastructure (Ollama, Redis, MCP) is disabled.</p>
 */
@SpringBootTest(
        classes = FileSystemTools.class,
        properties = "workshop.workspace.path=./workspace"
)
class FileSystemToolsIntegrationTest {

    @Autowired
    FileSystemTools fileSystemTools;

    @Test
    void listProjectFiles_returnsSampleProjectFiles() throws Exception {
        String files = fileSystemTools.listProjectFiles("sample-project");

        assertThat(files).contains("pom.xml");
        assertThat(files).contains("GreetingController.java");

        System.out.println("\n=== Lab 4 Project Files ===");
        System.out.println(files);
    }

    @Test
    void readFile_returnsPomContent() throws Exception {
        String content = fileSystemTools.readFile("sample-project/pom.xml");

        assertThat(content).contains("<groupId>com.example</groupId>");
        assertThat(content).contains("spring-boot");

        System.out.println("\n=== Lab 4 pom.xml (first 200 chars) ===");
        System.out.println(content.substring(0, Math.min(200, content.length())));
    }

    @Test
    void writeFile_andReadBack() throws Exception {
        String testContent = "// Generated by integration test\npublic class TestFile {}";
        fileSystemTools.writeFile("sample-project/src/main/java/com/example/TestFile.java", testContent);

        String readBack = fileSystemTools.readFile("sample-project/src/main/java/com/example/TestFile.java");
        assertThat(readBack).isEqualTo(testContent);

        System.out.println("\n=== Lab 4 Write/Read Verified ===");
    }

    @Test
    void pathTraversal_isBlocked() {
        assertThatThrownBy(() -> fileSystemTools.readFile("../../etc/passwd"))
                .isInstanceOf(SecurityException.class)
                .hasMessageContaining("sandbox");
    }
}
